---
- name: Keys Remap to fix a few bugs in the keyboard
  become: no
  lineinfile:
    dest: "~/.Xmodmap"
    state: present
    backup: no
    create: yes
    line: "{{item}}"
  with_items:
    - 'keycode 104 = Return'
    - 'keycode 163 = Prior'
    - 'keycode 78 = Next'
    - 'keycode 95 = Home Home Home Home F11 F11 XF86Switch_VT_11'
    - 'keycode 96 = End End End End F12 F12 XF86Switch_VT_12'

- name: 3D Printer Cura | Add repository
  apt_repository: repo='ppa:thopiekar/cura' state=present

- name: "3D Printer Cura | ensure packages are present"
  apt: name={{item}} update_cache=yes
  with_items:
    - cura
    - cura-plugins-all
    - cura-extra-plugins-all

- name: "3D Printer Repetier | ensure dependencies are installed"
  apt: name={{item}} update_cache=yes
  with_items:
    - mono-reference-assemblies-2.0
    - mono-devel
