---
- name: install base debian packages
  apt: name={{item}} state=latest
  with_items:
    - cpufreqd
    - aptitude
    - cpufrequtils
    - hdparm
    - udev
    - ntfs-3g
    - htop
    - iotop
    - iftop
    - mosh
    - vim
    - tmux
    - zsh
    - wget
    - curl
    - tree
    - ncdu
    - git
    - unattended-upgrades
    - curl
    - wget
    - rsync
    - toilet

- name: update & upgrade
  apt: update_cache=yes upgrade=full cache_valid_time=3600
