---
default_tmpfs_mount_Options: defaults,noatime,nosuid
mounts:
  - {
    mountDirName: "/tmp",
    mountOptions: "{{default_tmpfs_mount_Options}},size=200m",
    }
  - {
    mountDirName: "/var/tmp",
    mountOptions: "{{default_tmpfs_mount_Options}},size=100m",
    }
  - {
    mountDirName: "/var/log",
    mountOptions: "{{default_tmpfs_mount_Options}},mode=0755,size=100m",
    }
